#!/usr/bin/env ruby

require_relative 'lib/mingle_link_fixer'

fixer = Mingle::LinkFixer.new(credential_file: '/Users/wdephill/Downloads/credentials.csv',
                              project_url: 'http://localhost:8080/projects/test')
fixer.fix(dry_run: true)
