#!/usr/bin/env ruby

require 'optparse'
require 'mingle_events'

base = File.expand_path(__dir__)

params = {}
OptionParser.new do |opts|
  opts.banner = "Usage: #{$0} [options]"

  opts.on("-k", "--key [KEY]", "auth key, can be generated on your profile page under the tab 'HMAC Auth Key'") do |key|
   params[:key] = key
  end

  opts.on("-l", "--login [LOGIN]", "user login") do |login|
   params[:login] = login
  end

  opts.on("-u", "--url [URL]", "url, e.g. http://mingle.your.org/projects/my_project") do |url|
   params[:host], params[:project_identifier] = url.split("/projects/")
  end

  opts.on("-t", "--test", "TEST MODE: do not do any updates, just print stuff out") do |t|
   params[:mingle] = t
  end

  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end
end.parse(ARGV)

puts "[DEBUG] params => #{params.inspect}"


access = MingleEvents::MingleHmacAuthAccess.new(params[:host], params[:login], params[:key])

event_fetcher = MingleEvents::ProjectEventFetcher.new(params[:project_identifier], access)

event_fetcher.all_fetched_entries.each do |e|
  puts "[DEBUG] e => #{e.inspect}"
end
